# Generated by Django 5.0.7 on 2024-08-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudonym', models.CharField(max_length=40, verbose_name='seudonimo')),
            ],
        ),
        migrations.CreateModel(
            name='libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=14)),
                ('title', models.CharField(max_length=40, verbose_name='titulo')),
                ('synopsis', models.TextField(max_length=2000, verbose_name='sinopsis')),
                ('publication_date', models.DateField(verbose_name='fecha de publicacion')),
                ('front_page', models.FileField(upload_to='', verbose_name='portada')),
                ('classification', models.FloatField(verbose_name='clasificacion')),
                ('authors', models.ManyToManyField(related_name='autores', to='books.autor')),
            ],
        ),
    ]
