# Generated by Django 5.0.7 on 2024-08-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_autor_author_rename_libro_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='pseudonym',
            field=models.CharField(max_length=40, verbose_name='seudónimo'),
        ),
    ]
