# Generated by Django 5.0.7 on 2024-08-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seudonimo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=14)),
                ('titulo', models.CharField(max_length=40)),
                ('sinopnsis', models.TextField(max_length=2000)),
                ('fecha_publicacion', models.DateField()),
                ('portada', models.FileField(upload_to='')),
                ('clasificacion', models.FloatField()),
                ('autor', models.ManyToManyField(related_name='autores', to='home.autor')),
            ],
        ),
    ]
