# Generated by Django 5.0.7 on 2024-08-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_remove_libro_autor_delete_autor_delete_libro'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, verbose_name='Nombre de Usuario')),
                ('email', models.EmailField(max_length=254, verbose_name='correo')),
                ('password', models.CharField(max_length=16, verbose_name='contraseña')),
            ],
        ),
    ]
